MySQL:
    Enabled: false
    Username: root
    Password: pass
    Database: Minecraft
    Hostname: localhost
    Port: 3306
Ranks:
  1: Private
  2: Private I
  3: Private II
  4: Sergeant
  5: Sergeant I
  6: Sergeant II