# Wether the MOTD will be displayed when the player logs into the server
MOTD: The Server is a testing server for the plugin Skills
# Rank Names will be shown in chat, long names not recommended, there is no limit to ranks
MOTDEnabled: true
# Ranks will be displayed in chat, Long names are not recommended, There is no limit to number of ranks
Ranks:
    1: Private
    2: Private I
    3: Private II
    4: PFC
    5: PFC I
    6: PFC II
    7: Specialist
    8: Specialist I
    9: Specialist II
    10: Corporal
    11: Corporal I
    12: Corporal II
# Tokens can be used by /tokens
# The Tokens can be used on items listed below. Item Names must be exact. Numbers are for the amount of tokens needed
# Items will be given with Efficiency 3
Tokens:
    Iron_Pickaxe: 1
    Diamond_Pickaxe: 2
# Minimum payout for an event, based on Exp. Example 0.25 * STONE = $.25 or 0.25 * GOLD_ORE = $ 1
BasePay: 0.25
# Experience will only be given for the blocks listed here
Mining:
    Exp:
        Destroy:
            STONE: 1
            COBBLESTONE: 1
            SANDSTONE: 1
            EMERALD_ORE: 6
            QUARTZ_ORE: 4
            IRON_ORE: 3
            COAL_ORE: 2
            GOLD_ORE: 4
            DIAMOND_ORE: 5
            LAPIS_ORE: 4
            REDSTONE_ORE: 3
            MOSSY_COBBLESTONE: 3
Digging:
    Exp:
        Destroy:
            DIRT: 1
            GRASS: 1
            SAND: 1
            GRAVEL: 2
            CLAY: 2
            MYCEL: 2
Logging:
    Exp:
        Destroy:
            LOG: 2
            LEAVES: 1
Farming:
    Exp:
        Destroy:
            WHEAT: 2
            MELON_BLOCK: 2
            PUMPKIN: 2
        Place:
            SEEDS: 1
            MELON_SEEDS: 1
            PUMPKIN_SEEDS: 1
            SUGAR_CANE: 1
            COCOA: 1
            WATER_BUCKET: 2
            DIRT: 1
Building:
    Exp:
        Place:
            LOG: 2
            WOOD: 1
            GLASS: 3
            DISPENSER: 3
            WOOL: 2
            GLOWSTONE: 2
            QUARTZ_STAIRS: 6
            QUARTZ_BLOCK: 8
            LAPIS_BLOCK: 8
            EMERALD_BLOCK: 12
            DIAMOND_BLOCK: 10
            GOLD_BLOCK: 8
            IRON_BLOCK: 6
            BRICK: 3
            OBSIDIAN: 5
            WORKBENCH: 1
            CHEST: 1
            COBBLE_WALL: 2
            COBBLESTONE_STAIRS: 2
            COBBLESTONE: 1
            SIGN: 1
            SANDSTONE: 1
            SANDSTONE_STAIRS: 2
            FENCE: 1
            FENCE_GATE: 1
            ITEM_FRAME: 2
            LADDER: 1
Hunting:
    Exp:
        Kill:
            PLAYER: 10
            PIG: 2
            SHEEP: 2
            COW: 2
            SPIDER: 4
            SKELETON: 5
            ZOMBIE: 3
            BAT: 1
            CHICKEN: 1
            CREEPER: 4
            BLAZE: 5